#!/usr/bin/env bash
# redirect 404 page not found to custom message
# sets up a new 404 error page that contains
# the string: Ceci n'est pas une page.

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/custom_404.html
echo "server {
	listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index custom_404.html;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
	
	error_page 404 /custom_404.html;
	location = /custom_404.html {
	root /var/www/html;
	internal;
	}
}" > default

sudo mv -f default /etc/nginx/sites-enabled/default
sudo service nginx restart
